from __future__ import annotations

from typing import Any, TypedDict

from genson import SchemaBuilder


class InferenceResult(TypedDict):
    spec: dict[str, Any]
    fabricated: list[str]
    warnings: list[str]


def infer_openapi_from_payload(
    payload: dict[str, Any] | list[Any],
    *,
    resource_name: str = "resource",
    method: str = "POST",
) -> InferenceResult:
    """Infer a minimal OpenAPI 3.0.3 spec from a sample payload.

    Accepts a JSON object OR a JSON array (genson handles both).
    The path, method, operationId, and tags are FABRICATED — the caller
    should treat them as defaults to be reviewed/edited.
    """
    builder = SchemaBuilder(schema_uri=None)
    builder.add_object(payload)
    schema = builder.to_schema()
    schema.pop("$schema", None)
    schema = _to_openapi_3_0_schema(schema)

    op_id = f"{method.lower()}{resource_name[:1].upper()}{resource_name[1:]}"
    path = f"/{resource_name}s"

    spec: dict[str, Any] = {
        "openapi": "3.0.3",
        "info": {
            "title": f"Inferred from {resource_name} payload",
            "version": "0.1.0",
            "description": "Auto-generated by fhir-forge spec_inferer. Review fabricated fields.",
        },
        "paths": {
            path: {
                method.lower(): {
                    "operationId": op_id,
                    "summary": f"{method} {resource_name}",
                    "tags": [resource_name],
                    "responses": {
                        "200": {
                            "description": "OK",
                            "content": {
                                "application/json": {"schema": schema}
                            },
                        }
                    },
                }
            }
        },
    }

    fabricated = [
        f"paths.{path}",
        f"paths.{path}.{method.lower()}.operationId",
        f"paths.{path}.{method.lower()}.summary",
        f"paths.{path}.{method.lower()}.tags",
        "info.title",
    ]
    warnings = [
        "Path, HTTP method, operationId, tags and info.title are fabricated. "
        "Review them before converting to FHIR.",
    ]
    return {"spec": spec, "fabricated": fabricated, "warnings": warnings}


def _to_openapi_3_0_schema(schema: Any) -> Any:
    """Convert JSON Schema (genson draft-04 output) to OpenAPI 3.0.3 dialect.

    Genson emits ``type: "null"`` and ``type: ["string", "null"]`` for nullable
    fields. OpenAPI 3.0.3 doesn't allow ``type: null`` — uses ``nullable: true``.
    """
    if not isinstance(schema, dict):
        return schema

    out: dict[str, Any] = {}
    types = schema.get("type")
    if isinstance(types, list):
        non_null = [t for t in types if t != "null"]
        if "null" in types:
            out["nullable"] = True
        if len(non_null) == 1:
            out["type"] = non_null[0]
        elif len(non_null) > 1:
            out["oneOf"] = [{"type": t} for t in non_null]
    elif types == "null":
        out["type"] = "string"
        out["nullable"] = True
    elif types is not None:
        out["type"] = types

    if "properties" in schema:
        out["properties"] = {
            k: _to_openapi_3_0_schema(v) for k, v in schema["properties"].items()
        }
    if "items" in schema:
        out["items"] = _to_openapi_3_0_schema(schema["items"])
    for key in ("required", "format", "enum", "minimum", "maximum", "minLength", "maxLength"):
        if key in schema:
            out[key] = schema[key]
    return out
