from __future__ import annotations

import datetime as dt
import uuid
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from fhir_forge.state import ConversionState


_NARRATIVE_DIV = (
    '<div xmlns="http://www.w3.org/1999/xhtml">'
    "Generated by fhir-forge — {resource_type} resource"
    "</div>"
)


def _ensure_narrative(resource: dict[str, Any]) -> dict[str, Any]:
    """Inject a minimal generated narrative if the resource has none.

    Bundle, Parameters, and primitive types do not require dom-6.
    For DomainResource subtypes we add a placeholder text element.
    """
    if "text" in resource and resource["text"].get("div"):
        return resource
    rtype = resource.get("resourceType", "Resource")
    return {
        **resource,
        "text": {
            "status": "generated",
            "div": _NARRATIVE_DIV.format(resource_type=rtype),
        },
    }


def bundle_node(state: ConversionState) -> dict[str, Any]:
    """Assemble all valid FHIR resources into a FHIR R4 Bundle."""
    resources = state["fhir_resources"]
    warnings = list(state.get("warnings", []))

    # If we hit max retries, include invalid resources with a warning tag
    if state["retry_count"] >= 3 and state.get("invalid_resources"):
        for r in state["invalid_resources"]:
            rid = r.get("id", r.get("resourceType", "unknown"))
            warnings.append(f"Resource {rid} included despite validation errors (max retries reached)")
        resources = resources + list(state["invalid_resources"])

    resources = [_ensure_narrative(r) for r in resources]

    entries: list[dict[str, Any]] = [
        {"fullUrl": f"urn:uuid:{uuid.uuid4()}", "resource": r}
        for r in resources
    ]

    timestamp = dt.datetime.now(tz=dt.UTC).isoformat()
    bundle: dict[str, Any] = {
        "resourceType": "Bundle",
        "id": f"forge-{state['job_id']}",
        "type": "collection",
        "timestamp": timestamp,
        "meta": {
            "tag": [
                {
                    "system": "https://fhir-forge.example.com/tags",
                    "code": "generated",
                    "display": "Generated by fhir-forge",
                }
            ]
        },
        "entry": entries,
    }

    return {"fhir_resources": resources, "warnings": warnings, "_bundle": bundle}
